### ISSUE TITLE
Make library async

### ISSUE THREAD

**Issue by tulindo** [tulindo/tvchannellist#3]
Using aiohttp instead of sync with requests

**Comment by scop** [comment]
I think this would be a good thing in principle, but it will also be a major change for library users so it should be done as soon as possible.

**Comment by tulindo** [comment]
I see 2 ways:

1. Implement async ad engine level (this will allow to keep the same user interface)
2. Make the interface async (this will keep the engines unchanged)

Do you think the second option is better? 
Do you have an example of such an implementation?

**Comment by scop** [comment]
I think it would be better to go async all the way, engines and at least load_channels and get_providers async. I.e. both engines and parts of the user interface would change.

**Comment by tulindo** [comment]
Once you have load channels and get provider as async... What's the advantage in having also the engine working asynchronously?

**Comment by scop** [comment]
The program may be doing something equally or more interesting at the same time the library is loading channels and providers, and that would benefit from being async. To accomplish that, how would you implement it in a clean way if the engines weren't async under the hood, too? And as mentioned, one nice thing about aiohttp/aresponses -- which isn't really async related though -- is the ability to use captured responses dumps as is for testing/mocking. So if you like to be able to do that, it'll help with #2.

**Comment by tulindo** [comment]
The advantage of an async interface are clear (that's why I added this issue). But honestly I don't see the advantages of having also the internal request call as async. Maybe I'm wrong (as I said my knowledge of python is quite limitedl
@MartinHjelmare sorry to bother you... Feel free not to answer.. What do you think about this issue?

**Comment by MartinHjelmare** [comment]
If you're consider using asyncio I would totally recommend using it from top to bottom. It'll make working with the library a lot easier if you know that you're in the event loop the whole time unless explicitly scheduling something on the executor thread pool.

This doesn't mean all functions have to be coroutines. You can still run normal callbacks in the event loop. You just shouldn't do any regular I/O or blocking work in the event loop.

**Comment by tulindo** [comment]
Thanks @MartinHjelmare for your collaboration.
So let's go for a full async implementation!
Any working example (of async working requests based python module) or documentation is welcome.
Thanks.

**Comment by scop** [comment]
> async working requests based

I don't think such a thing exists (well I guess it might, but doesn't make much sense). If you want to go async, forget about requests, use aiohttp instead.

**Comment by tulindo** [comment]
@scop... Sorry my bad

**Comment by tulindo** [comment]
@MartinHjelmare sorry if I bother you again.
As explained in https://github.com/home-assistant/architecture/issues/335 I started this project in order  to be used by HA.
My question is: once integrated will HA take benefit from this project being implemented as async or not?
May I also ask your contribution for the above HA issue? 
Thanks

**Comment by MartinHjelmare** [comment]
Yes, we like asyncio.

I might comment later on the arch issue, when I've read up more.
